const PRODUCTS = [
  {
    id: 'bolsas-camisetas',
    name: 'Bolsas tipo camisetas blancas',
    category: 'otros',
    presentation: 'Pack de 380 unidades · 25 × 11 × 44 cm',
    price: 2660,
    currency: 'CUP',
    priceLabel: 'por pack',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/bolsas.png',
    description: 'Material HDPE, material virgen no reciclado.'
  },
  {
    id: 'nucleo-enzimatico',
    name: 'Núcleo Enzimático Panacea 0.2 %',
    category: 'reposteria-panaderia',
    presentation: 'Saco de 10 kg',
    price: 30000,
    currency: 'CUP',
    priceLabel: 'por saco',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/nucleo.png',
    description: ''
  },
  {
    id: 'maicena',
    name: 'Maicena',
    category: 'reposteria-panaderia',
    presentation: 'Saco de 25 kg',
    price: 30000,
    currency: 'CUP',
    priceLabel: 'por saco',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/maicena.png',
    description: 'Almidón de maíz modificado.'
  },
  {
    id: 'polvo-hornear',
    name: 'Polvo de hornear',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 25 kg',
    price: 101000,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/polvo.png',
    description: ''
  },
  {
    id: 'bicarbonato',
    name: 'Bicarbonato de sodio',
    category: 'reposteria-panaderia',
    presentation: 'Saco de 25 kg',
    price: 40500,
    currency: 'CUP',
    priceLabel: 'por saco',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/bicarbonato.png',
    description: 'Food grade. Origen España.'
  },
  {
    id: 'cobertura-blanco-negro',
    name: 'Cobertura de chocolate Blanco y Negro',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 20 kg',
    price: 95500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/blanco-negro.png',
    description: 'Cobertura blanca, cobertura especial y cobertura sucedáneo con leche.'
  },
  {
    id: 'manteca-macomsa',
    name: 'Manteca de cerdo pura fundida Macomsa',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 kg',
    price: 28500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'limited',
    stock: 80,
    image: 'assets/products/macomsa.png',
    description: ''
  },
  {
    id: 'manteca-masoliver',
    name: 'Manteca de cerdo Masoliver',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 13 kg',
    price: 41000,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/masoliver.png',
    description: ''
  },
  {
    id: 'manteca-multiuso',
    name: 'Manteca de cerdo Multiuso Casaponsa',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 12 kg',
    price: 35500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/multiuso.png',
    description: ''
  },
  {
    id: 'manteca-costa-brava',
    name: 'Manteca dura de cerdo Costa Brava',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 15 kg',
    price: 43500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/costa-brava.png',
    description: 'Origen España. Se obtiene del saín del cerdo. Ideal para panadería y repostería.'
  },
  {
    id: 'margarina-hojaldre',
    name: 'Margarina de hojaldre',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 kg',
    price: 32500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/margarina.png',
    description: ''
  },
  {
    id: 'nata-crem-pat',
    name: 'Nata vegetal Crem Pat',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 unidades',
    price: 32500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/nata-crem-pat.png',
    description: 'Nata vegetal Crem Pat, presentación 1 L.'
  },
  {
    id: 'nata-hole',
    name: 'Nata vegetal Hole',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 unidades',
    price: 33500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/nata-hole.png',
    description: 'Nata vegetal Hole, presentación 1 L.'
  },
  {
    id: 'nata-hulala',
    name: 'Nata vegetal Hulalá',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 unidades',
    price: 34500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/nata-hulala.png',
    description: 'Nata vegetal Hulalá, presentación 1 L.'
  },
  {
    id: 'supernortemul',
    name: 'Supernortemul',
    category: 'reposteria-panaderia',
    presentation: 'Cubeta de 5 kg',
    price: 101000,
    currency: 'CUP',
    priceLabel: 'por cubeta',
    availability: 'out',
    stock: 0,
    image: 'assets/products/supernortemul.png',
    description: ''
  },
  {
    id: 'redolmy',
    name: 'Redolmy',
    category: 'reposteria-panaderia',
    presentation: 'Cubeta de 19 kg',
    price: 101000,
    currency: 'CUP',
    priceLabel: 'por cubeta',
    availability: 'out',
    stock: 0,
    image: 'assets/products/redolmy.png',
    description: ''
  },
  {
    id: 'chocovic',
    name: 'Cobertura de chocolate Chocovic',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 kg',
    price: 95500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/chocovic.png',
    description: 'Cobertura de chocolate en chapillas.'
  },
  {
    id: 'levadura',
    name: 'Levadura seca instantánea Fabao',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 20 unidades',
    price: 41000,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/levadurafabao.png',
    description: 'Levadura seca instantánea, presentación Pack 500 gr'
  }
];
