const PRODUCTS = [
  {
    id: 'bolsas-camisetas',
    name: 'Bolsas tipo camisetas blancas',
    category: 'otros',
    presentation: 'Pack de 380 unidades · 25 × 11 × 44 cm',
    price: 2660,
    currency: 'CUP',
    priceLabel: 'por pack',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/otros/bolsas.jpg',
    description: 'Material HDPE, material virgen no reciclado.'
  },
  {
    id: 'nucleo-enzimatico',
    name: 'Núcleo Enzimático Panacea 0.2 %',
    category: 'reposteria-panaderia',
    presentation: 'Saco de 10 kg',
    price: 30000,
    currency: 'CUP',
    priceLabel: 'por saco',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/reposteria-panaderia/nucleo.jpg',
    description: ''
  },
  {
    id: 'maicena',
    name: 'Maicena',
    category: 'reposteria-panaderia',
    presentation: 'Saco de 25 kg',
    price: 30000,
    currency: 'CUP',
    priceLabel: 'por saco',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/reposteria-panaderia/maicena.jpg',
    description: 'Almidón de maíz modificado.'
  },
  {
    id: 'polvo-hornear',
    name: 'Polvo de hornear',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 25 kg',
    price: 101000,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/reposteria-panaderia/polvo.jpg',
    description: ''
  },
  {
    id: 'bicarbonato',
    name: 'Bicarbonato de sodio',
    category: 'reposteria-panaderia',
    presentation: 'Saco de 25 kg',
    price: 40500,
    currency: 'CUP',
    priceLabel: 'por saco',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/reposteria-panaderia/bicarbonato.jpg',
    description: 'Food grade. Origen España.'
  },
  {
    id: 'cobertura-blanco-negro',
    name: 'Cobertura de chocolate Blanco y Negro',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 20 kg',
    price: 95500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'unlimited',
    stock: null,
    image: 'assets/products/reposteria-panaderia/blanco-negro.jpg',
    description: 'Cobertura blanca, cobertura especial y cobertura sucedáneo con leche.'
  },
  {
    id: 'manteca-macomsa',
    name: 'Manteca de cerdo pura fundida Macomsa',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 kg',
    price: 28500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'limited',
    stock: 80,
    image: 'assets/products/reposteria-panaderia/macomsa.jpg',
    description: 'LA COMPRA MÁXIMA POR CLIENTE PARA ESTE PRODUCTO ES DE XX UNIDADES'
  },
  {
    id: 'manteca-masoliver',
    name: 'Manteca de cerdo Masoliver',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 13 kg',
    price: 41000,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/masoliver.jpg',
    description: 'LA COMPRA MÁXIMA POR CLIENTE PARA ESTE PRODUCTO ES DE XX UNIDADES'
  },
  {
    id: 'manteca-multiuso',
    name: 'Manteca de cerdo Multiuso Casaponsa',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 12 kg',
    price: 35500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/multiuso.jpg',
    description: 'LA COMPRA MÁXIMA POR CLIENTE PARA ESTE PRODUCTO ES DE XX UNIDADES'
  },
  {
    id: 'manteca-costa-brava',
    name: 'Manteca dura de cerdo Costa Brava',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 15 kg',
    price: 43500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/costa-brava.jpg',
    description: 'LA COMPRA MÁXIMA POR CLIENTE PARA ESTE PRODUCTO ES DE XX UNIDADES'
  },
  {
    id: 'margarina-hojaldre',
    name: 'Margarina de hojaldre',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 kg',
    price: 32500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/margarina.jpg',
    description: ''
  },
  {
    id: 'nata-crem-pat',
    name: 'Nata vegetal Crem Pat',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 unidades',
    price: 32500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/nata-crem-pat.jpg',
    description: 'Nata vegetal Crem Pat, presentación 1 L.'
  },
  {
    id: 'nata-hole',
    name: 'Nata vegetal Hole',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 unidades',
    price: 33500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/nata-hole.jpg',
    description: 'Nata vegetal Hole, presentación 1 L.'
  },
  {
    id: 'nata-hulala',
    name: 'Nata vegetal Hulalá',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 unidades',
    price: 34500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/nata-hulala.jpg',
    description: 'Nata vegetal Hulalá, presentación 1 L.'
  },
  {
    id: 'supernortemul',
    name: 'Supernortemul',
    category: 'reposteria-panaderia',
    presentation: 'Cubeta de 5 kg',
    price: 101000,
    currency: 'CUP',
    priceLabel: 'por cubeta',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/supernortemul.jpg',
    description: ''
  },
  {
    id: 'redolmy',
    name: 'Redolmy',
    category: 'reposteria-panaderia',
    presentation: 'Cubeta de 19 kg',
    price: 101000,
    currency: 'CUP',
    priceLabel: 'por cubeta',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/redolmy.jpg',
    description: ''
  },
  {
    id: 'chocovic',
    name: 'Cobertura de chocolate Chocovic',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 10 kg',
    price: 95500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/chocovic.jpg',
    description: 'Cobertura de chocolate en chapillas.'
  },
  {
    id: 'levadura',
    name: 'Levadura seca instantánea Fabao',
    category: 'reposteria-panaderia',
    presentation: 'Caja de 20 unidades',
    price: 41000,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'out',
    stock: 0,
    image: 'assets/products/reposteria-panaderia/levadurafabao.jpg',
    description: 'Levadura seca instantánea, presentación Pack 500 gr'
  },
  {
    id: 'desodorante-hombre-mujer',
    name: 'Desodorante de hombre y mujer',
    category: 'aseo',
    presentation: 'Caja de 6 unidades',
    price: 6000,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/desodorantehombremujer.jpg',
    description: 'Frascos de 50 ml'
  },
  {
    id: 'limpiacristales',
    name: 'Limpiacristales c/Pistola',
    category: 'aseo',
    presentation: 'Caja de 8 unidades',
    price: 9700,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/limpiacristales.jpg',
    description: 'Frascos de 1L'
  },
  {
    id: 'lavavajillas',
    name: 'Lavavajillas concentrado',
    category: 'aseo',
    presentation: 'Caja de 12 unidades',
    price: 13500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/lavavajillas.jpg',
    description: 'Frascos de 1L'
  },
  {
    id: 'cepillo-dental-exceed',
    name: 'Cepillo dental oral-B Exceed',
    category: 'aseo',
    presentation: 'Pack de 12 unidades',
    price: 9900,
    currency: 'CUP',
    priceLabel: 'por pack',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/cepillo-dental-exceed.jpg',
    description: ''
  },
  {
    id: 'cepillo-dental-medio',
    name: 'Cepillo dental oral-B Medio',
    category: 'aseo',
    presentation: 'Pack de 12 unidades',
    price: 8100,
    currency: 'CUP',
    priceLabel: 'por pack',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/cepillo-dental-medio.jpg',
    description: ''
  },
  {
    id: 'pasta-dental-closeup',
    name: 'Pasta dental Close-Up 90gr',
    category: 'aseo',
    presentation: 'Caja de 54 unidades por pack de 9 unidades de 90gr',
    price: 6800,
    currency: 'CUP',
    priceLabel: 'por pack',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/pasta-dental-closeup.jpg',
    description: ''
  },
  {
    id: 'pasta-dental-closeup-infantil',
    name: 'Pasta dental Close-Up Infantil 65gr',
    category: 'aseo',
    presentation: 'Caja de 144 unidades por pack de 12 unidades de 65gr',
    price: 9625,
    currency: 'CUP',
    priceLabel: 'por pack',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/pasta-dental-closeup-infantil.jpg',
    description: ''
  },
  {
    id: 'pasta-dental-colgate',
    name: 'Pasta dental Colgate White Teeth 75gr',
    category: 'aseo',
    presentation: 'Pack de 12 unidades de 75gr',
    price: 11000,
    currency: 'CUP',
    priceLabel: 'por pack',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/pasta-dental-colgate.jpg',
    description: ''
  },
  {
    id: 'servilleta-100hojas',
    name: 'Servilleta doble blanca 100 hojas',
    category: 'aseo',
    presentation: 'Caja de 23 unidades',
    price: 25500,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/servilleta-100hojas.jpg',
    description: ''
  },
  {
    id: 'servilleta-140hojas',
    name: 'Servilleta doble blanca 140 hojas',
    category: 'aseo',
    presentation: 'Caja de 30 unidades',
    price: 54300,
    currency: 'CUP',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/servilleta-140hojas.jpg',
    description: ''
  },
  {
    id: 'toallas-de-microfibra',
    name: 'Toallas de microfibra',
    category: 'aseo',
    presentation: 'Compra mínima de 10 Pack',
    price: 1600,
    currency: 'CUP',
    priceLabel: 'por pack',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/aseo/toallas-de-microfibra.jpg',
    description: ''
  },
  {
    id: 'aceite-castrol',
    name: 'Aceite Castrol 20W-50',
    category: 'ferreteria',
    presentation: 'Formato de 4 litros',
    price: 36,
    currency: 'USD',
    priceLabel: 'por unidad',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/ferreteria/aceite-castrol.jpg',
    description: ''
  },
  {
    id: 'losa-gravel-calacatta-gold',
    name: 'Losa de cerámica Gravel Calacatta Gold',
    category: 'ferreteria',
    presentation: 'Cajas de 2 unidades.',
    price: 24,
    currency: 'USD',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/ferreteria/losa-gravel-calacatta-gold.jpg',
    description: 'Medidas 60x120cm'
  },
  {
    id: 'losa-vanity-silver',
    name: 'Losa de cerámica Vanity Silver',
    category: 'ferreteria',
    presentation: 'Cajas de 2 unidades.',
    price: 24,
    currency: 'USD',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/ferreteria/losa-vanity-silver.jpg',
    description: 'Medidas 60x120cm'
  },
  {
    id: 'losa-marmol-carrara',
    name: 'Losa de cerámica Mármol Carrara',
    category: 'ferreteria',
    presentation: 'Cajas de 2 unidades.',
    price: 27,
    currency: 'USD',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/ferreteria/losa-marmol-carrara.jpg',
    description: 'Medidas 60x120cm'
  },
  {
    id: 'losa-mainstream-sand-polish',
    name: 'Losa de cerámica Mainstream Sand Polish',
    category: 'ferreteria',
    presentation: 'Cajas de 2 unidades.',
    price: 24,
    currency: 'USD',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/ferreteria/losa-mainstream-sand-polish.jpg',
    description: 'Medidas 60x120cm'
  },
  {
    id: 'losa-denali-ash-polished',
    name: 'Losa de cerámica Denali Ash Polished',
    category: 'ferreteria',
    presentation: 'Cajas de 2 unidades.',
    price: 24,
    currency: 'USD',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/ferreteria/losa-denali-ash-polished.jpg',
    description: 'Medidas 60x60cm'
  },
  {
    id: 'losa-meek-pearl-pulida',
    name: 'Losa de cerámica Meek Pearl Pulida',
    category: 'ferreteria',
    presentation: 'Cajas de 2 unidades.',
    price: 24,
    currency: 'USD',
    priceLabel: 'por caja',
    availability: 'inlimited',
    stock: null,
    image: 'assets/products/ferreteria/losa-meek-pearl-pulida.jpg',
    description: 'Medidas 60x60cm'
  }
];
